-- MySQL Script generated by MySQL Workbench
-- 07/10/18 11:54:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema springcoretask1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema springcoretask1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `springcoretask1` DEFAULT CHARACTER SET utf8 ;
USE `springcoretask1` ;

-- -----------------------------------------------------
-- Table `springcoretask1`.`auditorium`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `springcoretask1`.`auditorium` (
  `idauditorium` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `numberOfSeats` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idauditorium`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `springcoretask1`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `springcoretask1`.`event` (
  `idevent` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `basePrice` DOUBLE NULL DEFAULT NULL,
  `rating` ENUM('LOW', 'MID', 'HIGH') NULL DEFAULT 'LOW',
  PRIMARY KEY (`idevent`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `springcoretask1`.`seance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `springcoretask1`.`seance` (
  `event_id` INT(11) NOT NULL,
  `auditorium_id` INT(11) NOT NULL,
  `dateTime` DATETIME NOT NULL,
  PRIMARY KEY (`event_id`, `dateTime`, `auditorium_id`),
  INDEX `PK` (`event_id` ASC, `auditorium_id` ASC, `dateTime` ASC),
  INDEX `auditorFK_idx` (`auditorium_id` ASC),
  CONSTRAINT `eventFK`
    FOREIGN KEY (`event_id`)
    REFERENCES `springcoretask1`.`event` (`idevent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `auditorFK`
    FOREIGN KEY (`auditorium_id`)
    REFERENCES `springcoretask1`.`auditorium` (`idauditorium`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `springcoretask1`.`seat_vip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `springcoretask1`.`seat_vip` (
  `number` INT(11) NULL DEFAULT NULL,
  `auditor` INT(11) NULL DEFAULT NULL,
  INDEX `auditKF_idx` (`auditor` ASC),
  INDEX `PK` (`number` ASC, `auditor` ASC),
  CONSTRAINT `auditKF`
    FOREIGN KEY (`auditor`)
    REFERENCES `springcoretask1`.`auditorium` (`idauditorium`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `springcoretask1`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `springcoretask1`.`user` (
  `iduser` INT(11) NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL DEFAULT NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `birthday` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `springcoretask1`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `springcoretask1`.`ticket` (
  `idticket` INT(11) NOT NULL AUTO_INCREMENT,
  `dateTime` DATETIME NULL DEFAULT NULL,
  `user` INT(11) NULL DEFAULT NULL,
  `event` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idticket`),
  INDEX `userFK_idx` (`user` ASC),
  INDEX `eventFK_idx` (`event` ASC),
  CONSTRAINT `eventFKTicket`
    FOREIGN KEY (`event`)
    REFERENCES `springcoretask1`.`event` (`idevent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `userFK`
    FOREIGN KEY (`user`)
    REFERENCES `springcoretask1`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
